---
# Form running gradle locally
server:
  port: 8090

spring:
  datasource:
    url: jdbc:h2:file:./h2/oocl-agile-fs
    driverClassName: org.h2.Driver
    username: sa
    password: 1234
    jpa:
      databse-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2
  profiles:
    active: local
